services:
  user-api:
    container_name: user-api
    restart: on-failure
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/src
    env_file:
      - .env
    networks:
      - calculus-network

networks:
  calculus-network:
    external: true
    